[package]
name = "lifehash"
version = "0.1.0"
edition = "2021"

[lib]
name="lifehash_lib"
path="src/lib.rs"

[[bin]]
name="lifehash"
path="src/main.rs"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
hex = "0.4.3"
png = "0.17.15"
sha2 = "0.10.8"
